###
# computation config keys
output_dir: ./_computed-notebooks
default_kernel_name: TPAC_O2
project: USIO0030

###
# book table of contents
book_toc:
  format: jb-book
  root: description
  parts:
    - caption: Tracer snapshot
      chapters:
        - file: tracer_snapshot
    - caption: Tracer mean
      chapters:
        - file: tracer_mean

###
# book _config.yml keys
book_config_keys:
  title: Tropical Pacific Oxygen Dynamics at the Mesoscale
  repository:
    url: https://github.com/Eddebbar/TPAC_O2
    path_to_book: notebooks
    branch: main

###
# computational notebooks
compute_notebooks:  

  description:
    use_cluster: False
    parameter_groups:
      none:
        casename: *casename

  tracer_snapshot:
    use_cluster: True
    kernel_name: TROP_O2
    default_params:
      casename: *casename
      component: pop
      stream: h
    parameter_groups:
      temperature:
        variable_id: TEMP
      oxygen:
        variable_id: O2

  tracer_mean:
    use_cluster: True
    kernel_name: TROP_O2
    default_params:
      casename: *casename
      component: pop
      stream: h
    parameter_groups:
      temperature:
        variable_id: TEMP
      oxygen:
        variable_id: O2